### ISSUE TITLE
:bug: fix(core): Cannot build after upgrade 19.2.0 to 19.3.0

### ISSUE THREAD

**Issue by mmarinkov** [baloise/design-system#1749]
### Current Behavior

IBMx reported to have follwoing error when building the project after upgrading to 19.3.0:

Rollup: Unresolved Import
Could not resolve "./components" from "node_modules/@baloise/ds-core/dist/collection/index.js"

We could not reproduce this issue on our side.

### Expected Behavior

A bug happened!

### Steps to Reproduce

cannot reproduce

### Version

19.3.0

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
