### ISSUE TITLE
BalSelect typeahead fail when the reactive value that dynamically create the BalSelectOption is modified

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#312]
I first create a reactive value in setup()

```js
const postalCodeSuggestions = ref([])
```

The template:
```js
....
 <BalField :loading="postalCodeLoading" expanded>
    <BalFieldLabel>{{ t('registration.personal_info.zip') }}</BalFieldLabel>
    <BalFieldControl>
      <BalSelect v-model="postalCode"  @balInput="handlerPostalCodeAutocomplete" :name="postalCodeName" :loading="postalCodeLoading" typeahead expanded placeholder="1000">
        <BalSelectOption v-for="suggestion in postalCodeSuggestions" :key="suggestion.ONRP" :value="suggestion.TownName" :label="`${suggestion.ZipCode} - ${suggestion.TownName}`" >
          <b style="display: block">{{ suggestion.ZipCode }}</b>
          <span>{{ suggestion.TownName }}</span>
        </BalSelectOption>
      </BalSelect>
    </BalFieldControl>
    <BalFieldMessage color="danger">{{ postalCodeErrorMessage }}</BalFieldMessage>
  </BalField>
...
```

Assigning a array of object to postalCodeSuggestions  works when done in setup (before dom render) **but**  generate an error `TypeError: valuesArray.filter is not a function at HTMLElement.render` when modified after, in a promise cfor example

```js
api.addressAutocomplete({zipCode: postalCodeInput})
            .then((response) => {
              if(response.status == 200) {
                postalCodeSuggestions.value = [{'TownName': 'Gulu', 'ZipCode': '1300'},{'TownName': 'sdfsdf', 'ZipCode': '344'}, {'TownName': 'Fribourg', 'ZipCode': '1700'}]
              }
            })

```

**Comment by gagarine** [comment]
Mmmh perhaps it's somethings else. I will double check monday.

**Comment by gagarine** [comment]
@hirsch88 do you know when you have the time to check this bug? This is a blocking issue on our side.

**Comment by hirsch88** [comment]
@gagarine hopefully this week, but it looks more like next one, but If you like please create a PR.

**Comment by gagarine** [comment]
Thanks. Sadly I have no time for a PR (those bugs already are taking quiet a bit of extra time :/ )

**Comment by hirsch88** [comment]
Hi @gagarine 

I tried to reproduced it with the following example, but it worked with the Version 1.6.2.
Did I miss something in my example ?

```vue
<template>
  <BalCard class="has-margin-top">
    <BalCardTitle>Select</BalCardTitle>
    <BalCardContent>
      <BalSelect v-model="value" typeahead @bal-change="onChange($event)">
        <BalSelectOption
          v-for="opt in options"
          :key="opt.value"
          :label="opt.label"
          :value="opt.value"
        >
          {{ opt.label }}
        </BalSelectOption>
      </BalSelect>
      <p>{{ value }}</p>
    </BalCardContent>
  </BalCard>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'
import {
  NewBalOptionValue,
  BalOptionValue,
} from '@baloise/design-system-components'
import {
  BalSelect,
  BalSelectOption,
  BalCard,
  BalCardContent,
  BalCardTitle,
} from '@baloise/design-system-components-vue'

export default defineComponent({
  setup() {
    const value = ref([])
    const options = ref<BalOptionValue[]>([])

    const onChange = (newValue: string[]) => {
      console.log('change', newValue)
    }

    setTimeout(() => {
      options.value = [
        ...options.value,
        NewBalOptionValue('1', 'Label 1'),
        NewBalOptionValue('2', 'Label 2'),
        NewBalOptionValue('3', 'Label 3'),
        NewBalOptionValue('4', 'Label 4'),
      ]
    }, 2000)

    return {
      value,
      options,
      onChange,
    }
  },
  components: {
    BalSelect,
    BalSelectOption,
    BalCard,
    BalCardContent,
    BalCardTitle,
  },
})
</script>
```

**Comment by gagarine** [comment]
It works now!
Perhaps I didn't have the proper version? I updated vuejs and baloise and it worked directly (what a satisfaction ;))

I really appreciate your support. Now I think most of the problems are fixed with Baloise DS. Especially now that validators are working it's going to be a lot more easier.
